### ISSUE TITLE
Not working in Qt Quick project, locking up

### ISSUE THREAD

**Issue by somlioy** [Elypson/ChartJs2QML#1]
Hello. Great work on this project, but I can't get it to work in a QtQuick 2 project.

I've created a empty QtQuick project and added your Chart.bundle.js, Chart.qml and main.qml to the project. Also added `visible: true` to the Window object in main.qml

When trying to run the project the the executable shows up as a white window and just locks up and "stops answering". 

Any suggestions?

Compiling for Qt 5.12, Windows 10.

**Comment by somlioy** [comment]
Updating to latest version of Qt Creator and compiling to 5.12.7 seems to have fixed the issue somehow. Atleast I'm able to get the plots showing and the its not locking up anymore.

**Comment by Elypson** [comment]
Thank you for your information and good to hear that it works now!

Concerning your previous issue, did you also try to run `animationExample.qml` or just `main.qml` when this happened? Locking up sounds strange, there was no console output, I suspect? Locking should only happen if there is some infinite loop/recursion in JavaScript due to some error, or when Qt itself has a bug. I myself use Qt5.13.2.

**Comment by somlioy** [comment]
Can't remember everything I tried, but I tried pretty much everything from bare minimal to your main.qml. No console output.

Havent done much testing yet bit everything seems to work as expected so far (except for the legend dashed line appearance).
However I've noticed that there's an error output if mousing over the window when the application starts. But the tooltips works etc. Will report back if I notice something odd.

> qrc:/Chart.qml:60: TypeError: Property 'handler' of object QQuickMouseArea_QML_1(0x2320dd40) is not a function

I would suggest to at least make ChartJs2QML compatible with Qt 5.12.7 since that is the latest and only LTS-version of Qt.

**Comment by Elypson** [comment]
Ah yes, at this point in time, `handler` is not yet defined. This error can be safely ignored, but we will introduce some check against `undefined` to remove the warning.

I will check to fix it with 5.12.7, if possible

Thanks for your valuable input!

**Comment by Elypson** [comment]
Having installed and used `qmlscene` of 5.12.7 with macOS, I can confirm that it also works. Strange

**Comment by Elypson** [comment]
Also note that we have fixed the dashed-line button... strangely, `setLineDash([])` does not seem to work with QML
