### ISSUE TITLE
parameter pass from event is undefined

### ISSUE THREAD

**Issue by eswizardry** [Elypson/ChartJs2QML#2]
I would like to get element data when clicking on the point.
I have a handler to get the data in the option like below:

```js
chartOptions: {
    return {
        maintainAspectRatio: false,
        responsive: true,
        hoverMode: 'nearest',
        intersect: true,
        title: { display: false},
        onClick: function(evt) {
               console.debug("Click"); // <-- the function is call and print 'click' when I click on the point
                jsChart.getElementsAtEvent(evt); // <-- not success due to 'evt' is undefined
               console.debug(evt);  // <-- 'evt' is undefined
          }
     }
}
```

Do you have any suggestions on how to get index or data when clicking on the point?

**Comment by eswizardry** [comment]
Sorry just look the code in Chart.qml and found event is injected by bindEvents.
So I can get the index of the point when click by below code

```
        onClicked: {
            var element = jsChart.getElementsAtEvent(event.mouseEvent)
            console.debug(element[0]._index)
        }
```

Sorry for make noise here :)

**Comment by Elypson** [comment]
No worries, make all the noise you want :) You were faster in getting the solution that I was in answering, though. Hope, you get some nice results with our adaptor!
Cheers, Michael
